version: '3'

services:

    # ------ WEB APPLICATION BLOCK ------ 

    web_api:
        container_name: web_api
        build:
            context: ./services/web_api/
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - ./services/web_api/:/var/www/
        links:
            - database:database
        depends_on:
            - database
        environment:
            DB_CONNECTION: mysql
            DB_HOST: database
            DB_PORT: 3306
            DB_DATABASE: spa
            DB_USERNAME: spa
            DB_PASSWORD: 123456789
        networks:
            - spa-network

    web_client:
        container_name: web_client
        image: node:12.7.0-buster
        volumes:
            - ./services/web_client/:/usr/src/app
        working_dir: /usr/src/app
        command: bash -c "npm install && npm run start"
        ports:
            - 9900:4100
        links:
            - web_api:web_api
        depends_on:
            - web_api
        networks:
            - spa-network

    web_server:
        container_name: web_server
        build:
            context: ./services/web_server/
            dockerfile: Dockerfile
        working_dir: /var/www
        volumes:
            - ./services/web_client/public/:/var/www/public/
        links:
            - web_api:web_api
        ports:
            - 9901:80
        networks:
            - spa-network

    # ------ DATABASE BLOCK ------ 

    database:
        container_name: database
        image: mysql:8.0.16
        restart: always
        command:
            - "--default-authentication-plugin=mysql_native_password"
        environment:
            TERM: linux
            LANG: "C.UTF-8"
            MYSQL_USER: spa
            MYSQL_PASSWORD: 123456789
            MYSQL_DATABASE: spa
            MYSQL_ROOT_PASSWORD: root
        networks:
            - spa-network

    adminer:
        container_name: adminer
        image: adminer:4.7.2
        ports:
            - 9902:8080
        restart: always
        depends_on:
            - database
        networks:
            - spa-network

networks:
    spa-network:
        driver: bridge
